version: "3.8"
services:
  robot-vacuum:
    image: robot-vacuum
    environment:
      DATABASE_URL: postgres://vacuum:vacuum@postgres/vacuum
      TZ: Europe/Berlin
    ports:
      - 5000:5000/tcp
    depends_on:
      postgres:
          condition: service_healthy

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: vacuum
      POSTGRES_USER: vacuum
      POSTGRES_DB: vacuum
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
